# Generated by Django 4.2.27 on 2025-12-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('resume_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecole', models.CharField(max_length=255)),
                ('diplome', models.CharField(max_length=255)),
                ('date_debut', models.CharField(blank=True, max_length=50)),
                ('date_fin', models.CharField(blank=True, max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=255)),
                ('date_debut', models.CharField(blank=True, max_length=50)),
                ('date_fin', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.person')),
            ],
            options={
                'ordering': ['-ordre'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('niveau', models.IntegerField(default=80)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='core.person')),
            ],
        ),
    ]
