# Generated by Django 4.2.27 on 2025-12-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='niveau',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
